export const SET_SOCKET = "SET_SOCKET";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SOCKET_LOGOUT = "SOCKET_LOGOUT";
export const SOCKET_CLEAR_STATE = "SOCKET_CLEAR_STATE";
export const RESOLVE_BROWSER_CLOSE = "RESOLVE_BROWSER_CLOSE";

export const SET_USER_LIST = "SET_USER_LIST";
export const ADD_NEW_USER = "ADD_NEW_USER";
export const REMOVE_USER = "REMOVE_USER";

export const SET_QID = "SET_QID";
export const SET_DISPLAY_NAME = "SET_DISPLAY_NAME";
export const SET_QID_POPUP_DISPLAY_STATUS = "SET_QID_POPUP_DISPLAY_STATUS";
export const SET_INCORRECT_QID_POPUP_DISPLAY_STATUS = "SET_INCORRECT_QID_POPUP_DISPLAY_STATUS";
export const SET_SESSION_RESTORED_POPUP_DISPLAY_STATUS = "SET_SESSION_RESTORE_POPUP_DISPLAY_STATUS";

export const SET_CURRENTLY_PLAYING_INDEX = "SET_CURRENTLY_PLAYING_INDEX";
export const DECREMENT_CURRENTLY_PLAYING_INDEX = "DECREMENT_CURRENTLY_PLAYING_INDEX";
export const INCREMENT_CURRENTLY_PLAYING_INDEX = "INCREMENT_CURRENTLY_PLAYING_INDEX";
export const CHANGE_PLAY_STATE = "CHANGE_PLAY_STATE";
export const SEEK_SECONDS_AHEAD = "SEEK_SECONDS_AHEAD";
export const SET_VOLUME = "SET_VOLUME";
export const TOGGLE_SHUFFLE = "TOGGLE_SHUFFLE";
export const TOGGLE_MEDIA_DETAIL_MODAL = "TOGGLE_MEDIA_DETAIL_MODAL";

export const CHANGE_YOUTUBE_VIDEO_OBJECT = "CHANGE_YOUTUBE_VIDEO_OBJECT";
export const ADD_TO_QUEUE = "ADD_TO_QUEUE";
export const SET_QUEUE = "SET_QUEUE";
