export const CHANGE_PLAY_STATE = "CHANGE_PLAY_STATE";
export const CHANGE_YOUTUBE_VIDEO_OBJECT = "CHANGE_YOUTUBE_VIDEO_OBJECT";
export const ADD_TO_QUEUE = "ADD_TO_QUEUE";
export const SET_QUEUE = "SET_QUEUE";
