version: '3'
services:
    backend:
        build: ./backend
        ports:
            - "80:80"
        volumes:
            - ./frontend/mediaq/build:/build
            - ./backend/app.py:/app/app.py
            - ./backend/socket_constants.py:/app/socket_constants.py
	restart: always
    database:
        build: ./database
        ports:
            - "6379:6379"
        volumes:
            - ./database/redis_data:/data
	restart: always
