version: '3'
services:
    frontend:
        restart: always
        build: ./frontend
        volumes:
            - ./frontend/mediaq/build:/app/build
            - ./frontend/mediaq/src:/app/src
            - ./frontend/mediaq/public:/app/public
        restart: always
    backend:
        build: ./backend
        ports:
            - "5000:80"
        volumes:
            - ./frontend/mediaq/build:/build
            - ./backend/app.py:/app/app.py
            - ./backend/socket_constants.py:/app/socket_constants.py
    database:
        build: ./database
        ports:
            - "6379:6379"
        volumes:
            - ./database/redis_data:/data