version: '3'
services:
    frontend:
        build: ./frontend
        volumes:
            - ./frontend/mediaq/build:/app/build
            - ./frontend/mediaq/src:/app/src
            - ./frontend/mediaq/public:/app/public
    backend:
        build: ./backend
        ports:
            - "80:80"
        volumes:
            - ./frontend/mediaq/build:/build
            - ./backend/app.py:/app/app.py
    database:
        build: ./database
        ports:
            - "6379:6379"
